modLoader = "javafml" #mandatory
loaderVersion = "${neoforge_loader_version_range}" #mandatory
license = "LGPLv3" # Review your options at https://choosealicense.com/.
issueTrackerURL = "https://github.com/moehreag/TooltipTexture/issues" #optional
[[mods]] #mandatory
modId = "tooltiptexture" #mandatory
version = "${version}" #mandatory
displayName = "TooltipTexture" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional (see https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/)
displayURL = "https://github.com/moehreag/TooltipTexture" #optional (displayed in the mod UI)
logoFile="${mod_id}.png" #optional
credits="${credits}" #optional
authors = "${mod_author}" #optional
description = '''${description}''' #mandatory (Supports multiline text)
[[mixins]]
config = "${mod_id}.mixins.json"
[[dependencies.tooltiptexture]] #optional
modId = "neoforge" #mandatory
mandatory = true #mandatory
versionRange = "[${neoforge_version},)" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "CLIENT" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'
[[dependencies.tooltiptexture]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "CLIENT"
